### ISSUE TITLE
CSS Issue

### ISSUE THREAD

**Issue by lyqht** [lupyuen/lupyuen.github.io#1]
Hello, I happened to chance upon your resume site after watching Engineers.SG's video on your IoT Mission! I am impressed with your layout until i reach the bottom...

![image](https://user-images.githubusercontent.com/35736525/70587041-d6a77600-1c03-11ea-9227-bfe0c1576f9d.png)

**Comment by lupyuen** [comment]
Fixed. Thanks :-)
