### ISSUE TITLE
PineCone 

### ISSUE THREAD

**Issue by FedericoCeratto** [lupyuen/lupyuen.github.io#2]
Hi,
Regarding https://lupyuen.github.io/articles/pinecone#hands-on-with-pinecone-bl602 
a board very similar to the PineCone is available on aliexpress: https://www.aliexpress.com/item/1005001452354979.html

**Comment by lupyuen** [comment]
Cool thanks! 🙂

**Comment by lupyuen** [comment]
I have linked the info to the article. Thanks!
