### ISSUE TITLE
Better Open Source Advocate

### ISSUE THREAD

**Issue by danielbarry** [lupyuen/lupyuen.github.io#3]
Regarding: https://lupyuen.github.io/articles/advocate

> Be Kinder

I think it's better to treat the problem at the source - rather than be kinder, try to be happier, and in doing so you will become kinder. Only happy people can be the best version on themselves :+1: 

Also of course don't underestimate how much awesome work and effort you've already done, which is in itself an act of kindness. As a general rule I also suggest not helping those who make no effort to help themselves, your time is limited and you will quickly burn yourself out teaching people things they could have easily found themselves.

> Keep on Writing and Committing

I would suggest to write a series of smaller pieces more regularly. Try to capture the moment and give progress updates. Currently your articles read more like mini-books, where there are actually a few ideas in there. By publishing smaller and more frequently, you can also get more feedback early on - so it's win-win.

> Timezone

Being in the wrong timezone is sometimes good too, not having to respond to millions of comments every waking moment allows me to get more work done :)

> Stay Healthy

Hypertension and high blood pressure is nothing to laugh at. I would suggest seriously considering the keto diet, it has done a lot to improve my health and I'm sure it could do a lot for you too.  You can't make an awesome open source future if your ticker packs up too early!

Keep up the great work!

**Comment by lupyuen** [comment]
Thank you so much! Yep I'll consider the suggestions 🙂
