### ISSUE TITLE
Cannot debug in vscode: Configured debug type 'gdb' is not supported

### ISSUE THREAD

**Issue by lstolcman** [lupyuen/lupyuen.github.io#5]
Hi,

I'm trying to set up debugging rust in vscode. I'm following your tutorial, everything works good until the `Click Run → Start Debugging` step - throws error `Configured debug type 'gdb' is not supported`:
(https://github.com/lupyuen/lupyuen.github.io/blob/master/src/debug.md#debug-rust-firmware-with-vscode)
![obraz](https://user-images.githubusercontent.com/4583553/106518996-ef937a80-64da-11eb-8188-b3ba07d3a8f9.png)

It says, to set up gdb debugging, an extension is needed - could you show your vscode extension list?

I have such extensions installed:
![obraz](https://user-images.githubusercontent.com/4583553/106519189-38e3ca00-64db-11eb-8422-24792ea31da6.png)

Or it may be not an extension issue... Any help is appreciated.

Version of vscode: 1.52.1
System: Windows 10

Thanks

**Comment by lupyuen** [comment]
Hi: Thanks for submitting the issue. I have moved the issue for easier tracking: https://github.com/lupyuen/pinecone-rust/issues/1

Please gimme some time to check on this. Thanks! :-)

**Comment by thanksmia** [comment]
how about fixing it providing a correct .json file

**Comment by thanksmia** [comment]
for me the solution was switching over to vscodium removing vscode including the .extensions in C:\Users\mia\.vscode\extensions then get  open  source version of vscode called vscodium, get the c++ intellisense debugger tools etc... adding this  to get the vscode shop to codium


Creat a product.json file and put it in ...

Windows: %APPDATA%\VSCodium or %USERPROFILE%\AppData\Roaming\VSCodium
macOS: ~/Library/Application Support/VSCodium
Linux: $XDG_CONFIG_HOME/VSCodium or ~/.config/VSCodium
with the content:


{
  "extensionsGallery": {
    "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
    "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
    "itemUrl": "https://marketplace.visualstudio.com/items",
    "controlUrl": "",
    "recommendationsUrl": ""
  }
}

**Comment by thanksmia** [comment]
Don't also forgett to get the regular "visual studio" , win  and  search for  "enviroment" add  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64 

to Path like for your compilers  too.
