### ISSUE TITLE
Instructions for "Preview PineTime Watch Faces in your Web Browser with WebAssembly"

### ISSUE THREAD

**Issue by CMMUX** [lupyuen/lupyuen.github.io#6]
Reference - https://lupyuen.github.io/pinetime-rust-mynewt/articles/simulator

The problem appears to be inaccurate, incomplete, or out-dated instructions.

I can't get item 3 "Add GitHub Actions to our Fork" to work.

So far it has failed with two errors:

1) Incorrect path in "Copy WatchFace.cpp to LVGL for WebAssembly"
This was simply fixed by supplying the path in lowercase characters, instead of mixed case.

Please see - https://github.com/CMMUX/InfiniTime/runs/3644438471?check_suite_focus=true if you wish to correct your simulate.yml.

2) Unable to find "date/date.h" in "Build LVGL for WebAssembly".

Please see -  https://github.com/CMMUX/InfiniTime/runs/3644468978?check_suite_focus=true

Please advise how to fix this issue or produce a fix, so I can continue with the instructions.

Thank you for your help.

**Comment by lupyuen** [comment]
Hi: Sorry I'm no longer maintaining the PineTime Simulator.

Could you check this Reddit discussion for updates, or post your question there? Thanks :-)

https://www.reddit.com/r/PINE64official/comments/p6u17i/problems_with_pinetime_watch_face_simulator/

**Comment by CMMUX** [comment]
Ah, right, I see. I don't use reddit, but thanks anyway.

May I make a suggestion? Please could you put a publishing date on your articles? 
I didn't realise this one is over a year old, and would have looked for something more recent knowing this.
Yes, I know, the picture has 9 Aug 2020, but it doesn't really mean anything, and it didn't really register with me until now. A date, clearly visible at the beginning of the article would be good.

It would warn readers that due to its age, things might not work out as intended.

I'll get in touch with the maintainers of the simulator.

Thanks for your help.

**Comment by lupyuen** [comment]
Yep thanks in my newer articles I put the date right after the Table of Contents, without any pics.

Sorry I can't move the date any higher, my Markdown-To-HTML Generator (rustdoc), won't allow it.

**Comment by CMMUX** [comment]
No worries, that sounds great!

Thanks, & best wishes.
