### ISSUE TITLE
flash dt-bl10 board, using openocd

### ISSUE THREAD

**Issue by ntn888** [lupyuen/lupyuen.github.io#7]
Hi hope you are well...

I've sucessfully connected to the above board using openocd (via jtag):
```
jtag
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Versaloon(0x15)by Simon(compiled on Dec 21 2018)
Info : USB_TO_XXX abilities: 0x00000208:0x010001E3:0xC0000007
Info : clock speed 100 kHz
Warn : There are no enabled taps.  AUTO PROBING MIGHT NOT WORK!!
Info : JTAG tap: auto0.tap tap/device found: 0x20000c05 (mfg: 0x602 (<unknown>), part: 0x0000, ver: 0x2)
Warn : AUTO auto0.tap - use "jtag newtap auto0 tap -irlen 5 -expected-id 0x20000c05"
Warn : gdb services need one or more targets defined
```
and I have a *.bin file compiled...
but im not sure how do I flash it from here, your article pointed that'll it will be mentioned in the following article, but i couldnt find it.
how do I issue the flash command?

**Comment by ntn888** [comment]
BTW, I'm using this diy stm32 bluepill project to turn it into a JTAG debugger: https://github.com/zoobab/versaloon. I think it's pretty cool!

![jtag debugger blue pill](https://i.imgur.com/YnjaM8Z.jpg)

**Comment by lupyuen** [comment]
Sorry JTAG and OpenOCD are not supported for flashing BL602...

https://lupyuen.github.io/articles/pinecone#other-flashing-tools

So we need to flash over UART instead...

https://lupyuen.github.io/articles/flash#flash-bl602-firmware-with-linux-macos-and-windows

**Comment by ntn888** [comment]
Oh I see. Thanks.

**Comment by lupyuen** [comment]
I have updated my articles to say that JTAG + OpenOCD can't be used for flashing BL602. Thank you so much for the sponsorship :-)

**Comment by ntn888** [comment]
cool! thanks, i'm glad to have found articles on this small board dt-bl10...

**Comment by lupyuen** [comment]
Yep lemme know if you have problems :-)

**Comment by ntn888** [comment]
there was a tgt_602.cfg openocd config file on the buffalo labs github from one of your links... i couldnt successfully use it though. and i'm not sure if it's actually flashing or just debugging in the RAM.
Anyway thanks for your pointers.. I'll dig and see if there has been any improvements

**Comment by lupyuen** [comment]
Seems tgt_602.cfg is used for debugging, not for flashing, according to this...

https://github.com/bouffalolab/bl_docs/blob/main/BL602_Openocd%26GDB/en/Introduction%20of%20OpenOCD%20and%20GDB.pdf

![image](https://user-images.githubusercontent.com/9960133/153868256-01a0a4c7-a509-4aa5-b5e5-52b5767d3560.png)

**Comment by ntn888** [comment]
ah i see thanks.
the guys at black magic probe are running some tests for chip support...

**Comment by lupyuen** [comment]
A couple of us folks are now having discussions with the Bouffalo Lab engineers about improving the flashing process, including JTAG and OpenOCD support for flashing. I'll keep you updated on the upcoming enhancements.

Meanwhile these articles might help you understand why the BL602 flashing process is so complex, and how I automated it with a Raspberry Pi...

-   ["BL602 EFlash Loader: Reverse Engineered with Ghidra"](https://lupyuen.github.io/articles/loader)

-   ["BL602 Bootloader"](https://lupyuen.github.io/articles/boot)

-   ["Auto Flash and Test NuttX on RISC-V BL602"](https://lupyuen.github.io/articles/auto)

**Comment by ntn888** [comment]
i think actually BL is using the siFive version of the openocd.. but i think this only works with ftdi probes...

**Comment by ntn888** [comment]
according to this: https://nuttx.apache.org/docs/latest/platforms/risc-v/bl602/index.html#debuging-with-openocd
